name: test
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI
        uses: actions/checkout@v2

      - name: Use Node 14
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          registry-url: "https://registry.npmjs.org"

      - name: Use cached node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            nodeModules-

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Typecheck
        run: yarn tsc --noEmit
        env:
          CI: true

      - name: Run ESLint
        run: yarn eslint .
        env:
          CI: true
